// examples/vue/src/App.vue
<script lang="ts">
export default {
  name: 'App',
  data: () => ({
    showAlert: true
  }),
}
</script>

<template>
  <div bp-layout="block gap:md">
    <bp-button @click="showAlert = !showAlert">hello there</bp-button>
    <bp-alert-group status="success" :hidden="!showAlert">
      <bp-alert closable @close="showAlert = false">General Kenobi...</bp-alert>
    </bp-alert-group>
  </div>
</template>

<style scoped>

</style>

// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  showAlert = true;
}

<bp-alert-group status="success" [hidden]="!showAlert">
  <bp-alert closable (close)="showAlert = false">hello there!</bp-alert>
</bp-alert-group>
