// examples/vue/src/App.vue
<script setup lang="ts">
  import { ref } from 'vue';
  import '@blueprintui/components/include/alert.js';
  import '@blueprintui/components/include/button.js';

  const showAlert = ref(false);
  const toggle = () => { showAlert.value = !showAlert.value }
</script>

<template>
  <div bp-layout="block gap:md">
    <bp-button @click="showAlert = !showAlert">hello there</bp-button>
    <bp-alert-group status="success" :hidden="!showAlert">
      <bp-alert closable @close="showAlert = false">General Kenobi...</bp-alert>
    </bp-alert-group>
  </div>
</template>

<style scoped>

</style>

// projects/examples/angular/src/app/app.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import '@blueprintui/components/include/alert.js';
import '@blueprintui/components/include/button.js';


@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  showAlert = true;
}

<div bp-layout="block gap:md">
  <bp-button (click)="showAlert = !showAlert">hello there</bp-button>

  <bp-alert-group status="success" [hidden]="!showAlert">
    <bp-alert closable (close)="showAlert = false">General Kenobi...</bp-alert>
  </bp-alert-group>
</div>
